### ISSUE TITLE
Some emojis are not displaying properly on browser like flags

### ISSUE THREAD

**Issue by athandle** [scttcper/ngx-emoji-mart#325]

**Comment by zwjohn** [comment]
This issue still exists, flags are displayed as letters. Can this be fixed?

![image](https://user-images.githubusercontent.com/19634524/120723234-5b90ea00-c49f-11eb-9295-7a11961d81bd.png)

**Comment by scttcper** [comment]
using native emojis would rely on them being available, using sprite emoji would always have them. Filtering the set of emojis you display is also an option
