### ISSUE TITLE
setTimeout handler is taking too much time

### ISSUE THREAD

**Issue by sunny-anuvadiya-kevit** [scttcper/ngx-emoji-mart#344]
While using in multiple component, this violation warning is coming causing my app to freeze. 

![image](https://user-images.githubusercontent.com/53612273/86350493-66843e80-bc80-11ea-8487-76cc014dbfd5.png)

Its causing from picker component's nested setTimeout()
![image](https://user-images.githubusercontent.com/53612273/86350543-79970e80-bc80-11ea-8b41-0ac9bc580fa3.png)
https://github.com/TypeCtrl/ngx-emoji-mart/blob/d3aaeeb20d2af312d5028308ad043fa274ef80f8/src/lib/picker/picker.component.ts#L256

**Comment by scttcper** [comment]
I wouldn't put multiple emoji-marts on any page. It has a massive number of divs and images
