### ISSUE TITLE
not all emojis displaying in picker

### ISSUE THREAD

**Issue by zpydee** [scttcper/ngx-emoji-mart#347]
I'm not sure if there is an option i'm missing, but it appears that not all emojis are displaying in the picker. By way of example, here's the Smileys & People category I'm seeing, which is missing many emojis (eg :thumbsup:, :point_up:)

![Screenshot 2020-07-16 at 13 14 55](https://user-images.githubusercontent.com/6129162/87665855-dd810300-c767-11ea-9e41-e918783d6fd4.jpg)

**Comment by scttcper** [comment]
hmm what options have you passed

**Comment by zpydee** [comment]
``` html
<emoji-mart
    [darkMode]="false"
    [style]="{ width: '100%' }"
    set="native"
    [isNative]="true"
    [skin]="skin"
    [showPreview]="false"
    (emojiClick)="onAddEmoji($event)"
></emoji-mart>
```

**Comment by scttcper** [comment]
Might be an older os/browser thing? Are there any errors?

**Comment by zpydee** [comment]
nope, nope & nope. dunno, i'll play a bit...

**Comment by harellevy** [comment]
@scttcper Same here. @zpydee what did you do to fix it? In my storybook, it shows all icons, in my application that uses the storybook component I can't see many of the icons. very similar to what I see here.

**Comment by harellevy** [comment]
angular 13
rxjs 7
ngx-emoji-mart 6.2

**Comment by harellevy** [comment]
<img width="295" alt="image" src="https://user-images.githubusercontent.com/2623446/171623108-4f1a6b9c-e694-4bdf-a62f-fdad049da173.png">
