### ISSUE TITLE
Emojis are not loading due to 404 error from UNPKG

### ISSUE THREAD

**Issue by Arxero** [scttcper/ngx-emoji-mart#348]
I am trying to use native set but it does not work also neither one works except the apple and twitter ones.
https://unpkg.com/emoji-datasource-native@5.0.1/img/native/sheets-256/64.png
![Screenshot_4](https://user-images.githubusercontent.com/30701352/89039567-f8986900-d34a-11ea-9a89-6d90238ab87d.png)

**Comment by scttcper** [comment]
Native should not be loading a emoji set because it is native. isNative to true and do not use a set

**Comment by Arxero** [comment]
okay, thank you for your input it seems to work the way you said it would, but its bad that for others like  'emojione', 'messenger', 'facebook' and 'google' does not work

**Comment by scttcper** [comment]
the url should look like `https://unpkg.com/emoji-datasource-google@5.0.1/img/google/sheets-256/64.png` its working in the demo. Emojione is no longer supported.

**Comment by Arxero** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/30701352/89059646-3a84d780-d36a-11ea-90d0-7314adcd48f0.png)
Yeah okay, so emojione and messenger ones are not working for sure or supported I guess. I will close the issue and thank you for replies and the help.
