### ISSUE TITLE
Some emojis displays like a white box 

### ISSUE THREAD

**Issue by gauthier909** [scttcper/ngx-emoji-mart#388]
![image](https://user-images.githubusercontent.com/49980650/130354988-21cfdaf3-6d7d-49d5-8886-c2f826e0d2a9.png)

I'm using angular 11 and ionic 5 and some emojis displays as a white box. I don't need to have all of them so if there is a way to just hide the ones that doesn't show is ok for me, is it possible ?

**Comment by EllaPortnov1** [comment]
Having the same issue with Angular 11
![image](https://user-images.githubusercontent.com/75306934/130583194-4dfc408a-6f1f-4cde-9428-a18a8d048669.png)

**Comment by scttcper** [comment]
#381
