### ISSUE TITLE
background on hover is not centered

### ISSUE THREAD

**Issue by gauthier909** [scttcper/ngx-emoji-mart#392]
![image](https://user-images.githubusercontent.com/49980650/132098324-a534d18c-fd2d-4d36-9b49-2da862fe936f.png)

I'm using angular 11 and ionic 5 and when I pass the mouse on an emoji, the grey background to highlight the emoji seems a bit to much on the left. Is it possible to center this ? 

Thanks

**Comment by scttcper** [comment]
#385
