### ISSUE TITLE
Switch to jsdelivr cdn - Couldn't find the requested file /img/apple/64/64.png in emoji-datasource-apple.

### ISSUE THREAD

**Issue by dkptp** [scttcper/ngx-emoji-mart#424]
Tried updating again, this time immediately hitting this error. Switch to this new cdn doesn't seem to work or isn't configured correctly. Have to downgrade again.

![image](https://github.com/scttcper/ngx-emoji-mart/assets/133096348/ccb413b7-1669-4fee-867c-9f4df261025e)

**Comment by dkptp** [comment]
> https://cdn.jsdelivr.net/npm/emoji-datasource-google@14.0.0/img/google/sheets-256/64.png is working for me

I don't really get your comment. Am I doing something wrong?
As you can see the working path you mention is different from the failing path that's in the component code.

@scttcper Line 10 in src/lib/picker/ngx-emoji/emoji.service.ts
`https://cdn.jsdelivr.net/npm/emoji-datasource-${set}@14.0.0/img/${set}/64/${sheetSize}.png`;

As you can see this doesn't follow the same structure as the path you commented.

It seems like this is a line that's used for retrieving the emoji sheets, which fails regardless of the set I use.

**Comment by Maker4You** [comment]
+1
browser console output(Error):
GET https://cdn.jsdelivr.net/npm/emoji-datasource-apple@14.0.0/img/apple/64/64.png **404**

**Comment by Maker4You** [comment]
<ngx-emoji>
<span>
<span style='background-image: url("https://cdn.jsdelivr.net/npm/emoji-datasource-apple@14.0.0/img/apple/64/64.png");'></span>
</span>
<ngx-emoji>

have to change to:
"https://cdn.jsdelivr.net/npm/emoji-datasource-apple@14.0.0/img/apple/**sheets-256**/64.png"

**Comment by Maker4You** [comment]
Fix:
Go to -> YourProject\node_modules\@ctrl\ngx-emoji-mart\fesm2022
Change line 33897 from:
const DEFAULT_BACKGROUNDFN = (set, sheetSize) => `https://cdn.jsdelivr.net/npm/emoji-datasource-${set}@14.0.0/img/${set}/64/${sheetSize}.png`;
to:
const DEFAULT_BACKGROUNDFN = (set, sheetSize) => `https://cdn.jsdelivr.net/npm/emoji-datasource-${set}@14.0.0/img/${set}/sheets-256/${sheetSize}.png`;
