### ISSUE TITLE
Update from version 3.1.0 to 6.2.0 cause malformed images on emoji lists

### ISSUE THREAD

**Issue by latchuk** [scttcper/ngx-emoji-mart#426]
![image](https://github.com/scttcper/ngx-emoji-mart/assets/2432928/291d126f-56af-4b9d-8b9b-159cf8049733)

Any one emoji is showing incorrectly after the update. Anyone can help me please?

**Comment by nitinw631** [comment]
@latchuk, did you find any solution to this issue?

For me, it's showing the wrong emojis.

"@angular/core": "^15.2.9",
"@ctrl/ngx-emoji-mart": "^8.2.0",

![Screenshot 2023-06-13 at 1 39 06 PM](https://github.com/scttcper/ngx-emoji-mart/assets/24602717/54e75d57-5bd6-4369-b3be-87d3864c664a)

**Comment by janderson2103** [comment]
![image](https://github.com/scttcper/ngx-emoji-mart/assets/106889826/124ce94b-8b39-4399-b781-e89b192fe69e)
I'm with the same problem.
Version: 8.2.0
Angular: 15.2

**Comment by ArizonaInkStudios** [comment]
I have the same problem with incorrect emojis showing.
Version: 8.2.0
Angular: 15.2

**Comment by latchuk** [comment]
I continue searching for a solution. The problem remains.

**Comment by santosh-reddy** [comment]
@latchuk @ArizonaInkStudios   <emoji-mart class="emoji-mart" set="twitter" **isNative="true"** *ngIf="isEmojiPickerVisible"
        [style]="{ position: 'absolute', bottom: '20px', right: '20px' }" (emojiSelect)="addEmoji($event)"
        title="Choose your emoji"></emoji-mart>

**Comment by shyamal890** [comment]
Any solutions to this problem?

**Comment by sagarchikhale** [comment]
I am facing same issue. getting different emoji

**Comment by scttcper** [comment]
i think the latest version should be fine
